[build]
  # Install deps, ensure expo-cli is available, then export the web build into frontend/web-build
  # Using a guarded approach so Netlify will succeed even if expo-cli isn't installed globally.
  # This project uses Create React App for the web build.
  command = "cd 'frontend' && npm ci --no-audit --no-fund && npm run build"
  publish = "frontend/build"

[context.production.environment]
  # Netlify sets NODE_ENV=production by default during build. If your app needs dev deps
  # to build with expo, you can override this or install expo-cli globally in the build command.
  # Example runtime env variables (set real values in Netlify UI):
  # For CRA, only variables prefixed with REACT_APP_ are exposed to the client.
  # Set these in the Netlify Site settings → Build & deploy → Environment.
  # REACT_APP_API_URL = "https://your-backend.example.com"
  # REACT_APP_SOCKET_URL = "https://your-backend.example.com"
